config/routes.rb
Rails.application.routes.draw do

  post '/users/:id/ban' => 'users#ban'
  post '/users/:id/unban' => 'users#unban'

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  resources :posts do
    resources :comments
  end


  resources :users, :only => [:show]

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if (current_user.userstatus == -1)
      flash.now[:alert] = 'You are banned, you can not create a post.'
      render 'new'
      return
    end

    if @post.title.blank?
      flash.now[:alert] = 'You can\'t have a post without a title.'
      render 'new'
      return
    end

    if @post.content.blank?
      flash.now[:notice] = 'You should put some content in your post.'
      render 'new'
      return
    end

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    if (current_user.id!=@post.user_id && current_user.userstatus != 1)
      flash[:notice] = 'This is someone else\'s post. You cannot change it'
      redirect_to @post
      return
    end
  end

  def update
    if (current_user.userstatus == -1)
      flash.now[:alert] = 'You are banned, you are not allowed to modify posts.'
      render 'new'
      return
    end

    if post_params[:title].blank?
      flash.now[:alert] = 'You can\'t have a post without a title.'
      render 'edit'
      return
    end

    if post_params[:content].blank?
      flash.now[:notice] = 'You should put some content in your post.'
      render 'edit'
      return
    end

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_paths
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title,:content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title
  = f.input :content
  = f.submit

app/views/posts/edit.html.haml
%h1 Edit post
= render "form"
%br
%span.post_control.cancel= link_to "Cancel", post_path

app/views/posts/index.html.haml
#posts
  - @posts.each do |post|
    .post
      %h2.post_name= link_to post.title, post

      %p.post_info
        Published at:
        = time_ago_in_words(post.created_at)
        by
        %span.post_autor
          = link_to post.user.username, post.user

app/views/posts/new.html.haml
%h1 New post

= render 'form'

app/views/posts/show.html.haml
#post_content
  %h1= @post.title
  .author
    author:
    = link_to @post.user.username, @post.user
  %p= @post.content

  %span.post_control.edit= link_to "Edit", edit_post_path(@post)
  %span.post_control.delete= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure you wanna delete the post?"}

  #comments
    %h3= "Comments for this post:"+@post.comments.count.to_s
    =render @post.comments

    %h3 Make a comment
    =render "comments/form"